<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:p="http://imobiliaria.org"
        targetNamespace="http://imobiliaria.org"
        elementFormDefault="qualified">

    <simpleType name="stringType">
        <restriction base="string"/>
    </simpleType>

    <simpleType name="integerType">
        <restriction base="integer"/>
    </simpleType>

    <simpleType name="decimalType">
        <restriction base="decimal"/>
    </simpleType>

    <element name="descricao" type="p:stringType"/>
    <element name="nome" type="p:stringType"/>
    <element name="email" type="p:stringType"/>
    <element name="telefone" type="p:stringType"/>

    <element name="rua" type="p:stringType"/>
    <element name="bairro" type="p:stringType"/>
    <element name="cidade" type="p:stringType"/>
    <element name="número" type="p:integerType"/>

    <element name="tamanho" type="p:decimalType"/>
    <element name="numQuartos" type="p:integerType"/>
    <element name="numBanheiros" type="p:integerType"/>

    <element name="valor" type="p:decimalType"/>

    <element name="proprietario">
        <complexType>
            <sequence>
                <element ref="p:nome"/>
                <choice minOccurs="0" maxOccurs="unbounded">
                    <element ref="p:email"/>
                    <element ref="p:telefone"/>
                </choice>
            </sequence>
        </complexType>
    </element>

    <element name="endereco">
        <complexType>
            <sequence>
                <element ref="p:rua"/>
                <element ref="p:bairro"/>
                <element ref="p:cidade"/>
                <element ref="p:número" minOccurs="0"/>
            </sequence>
        </complexType>
    </element>

    <element name="caracteristicas">
        <complexType>
            <sequence>
                <element ref="p:tamanho"/>
                <element ref="p:numQuartos"/>
                <element ref="p:numBanheiros"/>
            </sequence>
        </complexType>
    </element>

    <element name="imovel">
        <complexType>
            <sequence>
                <element ref="p:descricao"/>
                <element ref="p:proprietario"/>
                <element ref="p:endereco"/>
                <element ref="p:caracteristicas"/>
                <element ref="p:valor"/>
            </sequence>
        </complexType>
    </element>

    <element name="imobiliária">
        <complexType>
            <sequence>
                <element ref="p:imovel" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

</schema>